# Generated by Django 2.1.14 on 2019-11-28 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Carrera', '0003_auto_20191125_1912'),
        ('Alumno', '0003_auto_20191125_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='idCarrera',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Carrera.Carrera'),
        ),
    ]
