# Generated by Django 2.1.14 on 2019-11-28 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0004_alumno_idcarrera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='idCarrera',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Carrera.Carrera'),
        ),
    ]
