# Generated by Django 2.1.14 on 2019-11-28 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0008_auto_20191128_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='idCarrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Carrera.Carrera'),
        ),
    ]
