# Generated by Django 3.0 on 2019-12-06 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0012_auto_20191129_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='idCarrera',
        ),
    ]
