# Generated by Django 2.1.14 on 2019-11-26 01:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Carrera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='create',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AddField(
            model_name='carrera',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
