# Generated by Django 2.1.14 on 2019-11-26 01:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Carrera', '0002_auto_20191125_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
